# Default settings may go here.
openlmis.jdbc.url=jdbc:postgresql://192.168.60.141:5432/esigl_production
openlmis.jdbc.username=postgres
openlmis.jdbc.password=esigl123



openlmis.replication.jdbc.driverClassName=org.postgresql.Driver
openlmis.replication.jdbc.url=jdbc:postgresql://192.168.60.141/esigl_production
openlmis.replication.jdbc.username=postgres
openlmis.replication.jdbc.password=esigl123
openlmis.replication.conn.pool.maxPoolSize = 5
openlmis.replication.conn.pool.initialPoolSize = 1

jdbc.driverClassName=org.postgresql.Driver

mail.sending.flag=true
mail.sender.host=192.168.60.34
mail.sender.port=2525
mail.sender.from=EsiglNotify@npsp.ci
mail.sender.username=Rsc\\EsiglNotify
mail.sender.password=Es1glNot1F@y
mail.sender.protocol=smtp

# JavaMail-specific properties
mail.smtp.auth=true
mail.smtp.auth.mechanisms=LOGIN
mail.smtp.starttls.enable=false
mail.smtp.starttls.required=TLS
mail.smtp.ssl.enable=false
mail.smtp.ssl.trust=*
mail.smtp.quitwait=false
mail.smtp.from=EsiglNotify@npsp.ci
mail.smtp.debug=true

mail.base.url = 192.168.60.34
app.url = https://esigltest.npsp.ci/

toggle.email.attachment.simam = false

toggle.new.rnr.view = false

locales.supported=en, fr